name: GitHub Copilot Coding Agent

on:
  workflow_dispatch:
    inputs:
      task:
        description: "What do you want the Copilot Agent to do?"
        required: true

jobs:
  copilot-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: GitHub Copilot Agent Action
        uses: github/copilot-agent-action@v1
        with:
          task: ${{ github.event.inputs.task }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
