name: GitHub Copilot Coding Agent

description: >
  Run GitHub Copilot Agent to handle development tasks like refactoring,
  fixing bugs, or adding features to the Muslim Quran Video Editor project.

on:
  workflow_dispatch:
    inputs:
      task:
        description: "What do you want the Copilot Agent to do? (e.g., 'Optimize video export module')"
        required: true

jobs:
  copilot-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: GitHub Copilot Agent Action
        uses: github/copilot-agent-action@v1
        with:
          task: ${{ github.event.inputs.task }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
